# Generated by Django 4.1.7 on 2023-05-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=20, verbose_name='Скидка в %'),
            preserve_default=False,
        ),
    ]
