# Generated by Django 4.1.4 on 2023-05-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_phoneform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneForm',
        ),
    ]
