# Generated by Django 4.1.4 on 2023-05-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_phoneform'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=100, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Скидка в рублях'),
        ),
    ]
