# Generated by Django 4.1.4 on 2023-05-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_phone_alter_orderitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_mis',
            field=models.CharField(choices=[('PH', 'Телефон'), ('LT', 'Ноутбук'), ('SW', 'Умные часы'), ('TB', 'Планшет')], default='PH', max_length=2, verbose_name='Вид товара'),
        ),
    ]
