# Generated by Django 4.1.4 on 2023-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_type_mis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_mis',
            field=models.CharField(choices=[('Костюмы/спортивные', 'Костюмы/спортивные'), ('Костюмы/классические', 'Костюмы/классические'), ('Кофты', 'Кофты'), ('Блузы', 'Блузы'), ('Футболки', 'Футболки'), ('Брюки', 'Брюки'), ('Юбки', 'Юбки'), ('Платья', 'Платья'), ('Худи', 'Худи'), ('Свитера', 'Свитера'), ('Жакеты', 'Жакеты'), ('Ветровки', 'Ветровки'), ('Куртки', 'Куртки'), ('Пуховики', 'Пуховики')], default='Костюмы/спортивные', max_length=50, verbose_name='Вид товара'),
        ),
    ]
