# Generated by Django 4.1.7 on 2023-05-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_payment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='image',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение'),
        ),
    ]
