# Generated by Django 4.2.1 on 2024-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_type_mis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_mis',
            field=models.CharField(choices=[('горячее', 'KOST'), ('лапша', 'LAPSHA'), ('салаты', 'SALATI'), ('закуски', 'ZAKUZKI'), ('напитки ', 'NAPITKI ')], default='горячее', max_length=50, verbose_name='Вид товара'),
        ),
    ]
