# Generated by Django 4.2.1 on 2024-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_type_mis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_mis',
            field=models.CharField(choices=[('GORYCHI', 'горячее'), ('LAPSHA', 'лапша'), ('SALATI', 'салаты'), ('ZAKUZKI', 'закуски'), ('NAPITKI', 'напитки ')], default='GORYCHI', max_length=50, verbose_name='Вид товара'),
        ),
    ]
